
from django.db import migrations, models
# Generated by Django 4.2.2 on 2023-06-14 08:21


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='reg_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
