# Generated by Django 4.2.2 on 2023-06-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='is_student',
        ),
        migrations.AddField(
            model_name='newuser',
            name='role',
            field=models.CharField(choices=[('A', 'admin'), ('S', 'student')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default=None, max_length=1, null=True),
        ),
    ]
